<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="WebApplication40.About" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
<br />
<asp:Image ID="Image1" runat="server" Height="280px" ImageUrl="~/im/evde1.jpg" Width="467px" />
<h3 style="box-sizing: border-box; font-family: Arial; color: rgb(17, 17, 17); font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Tek Bacak Yukarıda Plank</strong></h3>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Bu hareket vücudun karın, omuz ve kalça bölgesini çalıştırmaktadır.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Harekete parmak uçlarınız yerde, sırtınız düz ve omuzlarınız bileklerinizle bir çizgi oluşturacak şekilde “plank” pozisyonunda başlayın. Nefes alın ve bir bacağınızı yavaşça sırtınızla düz hizada kalmaya devam edicek şekilde kaldırın. Yalnız bunu yaparken, sırtınızı zorlamadığınızdan emin olun. Karnınızı sıkın. Daha sonra bacağınızı başlangıç pozisyonuna getirin ve bunu yaparken nefes verin. Hareketi, diğer bacak için de uygulayın.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <asp:Image ID="Image2" runat="server" Height="262px" ImageUrl="~/im/evde2.jpg" Width="466px" />
</p>
<h3 style="box-sizing: border-box; font-family: Arial; color: rgb(17, 17, 17); font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Burpees</strong></h3>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Bu hareket vücudun, tüm bölgelerini çalıştırmaktadır.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Harekete, ayakta düz vaziyette durarak başlayın. Squat yaparak yere doğru çömelin. Daha sonra ellerinizi önünüze olacak şekilde zemine koyun ve ayaklarınızı zıplayıp arkaya atarak plank pozisyonuna gelin. Sonrasında, ayaklarını ellerinize doğru gene zıplyarak çekin. Ellerinizi havaya kaldırın ve ilk pozisyonunuza doğru zıplayarak gelin. Hareketi bu şekilde tekrarlayın.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <asp:Image ID="Image3" runat="server" Height="291px" ImageUrl="~/im/evde3.jpg" Width="477px" />
</p>
<h3 style="box-sizing: border-box; font-family: Arial; color: rgb(17, 17, 17); font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Side Plank</strong></h3>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Bu hareket vücudun karın, omuz ve iç bacak bölgelerini çalıştırmaktadır.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Harekete, alt kolunuzun üstünde durarak plank pozisyonunda başlayın. Dirseğinizin omzunuzla aynı hizada ve sırtınızın dümdüz olmasına dikkat edin. Belinizi ve sırtınızı yere değdirmekten kaçının.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Ya ayaklarınızı birbirinin üstüne koyarak ya da alt ayağınızla üst ayağınızın arkasında tutarak, bir bacağınızı yukarı doğru kaldırın. Bacakların yere değmesini önlemek için, kalçanızı yukarıya doğru çekin.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <asp:Image ID="Image4" runat="server" Height="310px" ImageUrl="~/im/evde4.gif" Width="473px" />
</p>
<h3 style="box-sizing: border-box; font-family: Arial; color: rgb(17, 17, 17); font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Ski Jumps</strong></h3>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Bu hareket vücudun, kalça ve bacak bölgelerini çalıştırmaktadır.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Harekete, dizlerinizi hafifçe kırarak başlayın. Hareketi yaparken, göğsünüzün dik ve sırtınızın düz olduğuna emin olun.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    İki ayağınızla beraber sola doğru yavaşça yarı squat pozisyonuna gelip zıplayın. Zıpladıktan sonra yere ağırlığınız parmak ucunda değil, topukta olacak şekilde inin. Daha sonra aynı hareketi sağ tarafa doğru yapın ve bu şekilde yapmaya devam edin.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <asp:Image ID="Image5" runat="server" Height="274px" ImageUrl="~/im/evde5.jpg" Width="537px" />
</p>
<h3 style="box-sizing: border-box; font-family: Arial; color: rgb(17, 17, 17); font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 700;">Lunge Dips</strong></h3>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Bu hareket vücudun, kalça bölgesini çalıştırmaktadır.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    Hareket ayakta düz pozisyonda durarak başlayın. Ellerinizi belinize koyun. Sağ ayağınızı arkaya doğru parmak ucunuz yere değecek şekilde “lunge” pozisyonunda uzatın. Sol ayak topuğunuzu yere sabitleyin ve sonra sol dizinizi 90 derece olacak şekilde kırın. Sağ diziniz yere değmeyecek ve üst bedeninizi oynatacak şekilde yukarı doğru yükselip alçalın. Hedeflediğiniz tekrar sayısına ulaştıktan sonra, başlama pozisyonuna geri dönün ve hareketi diğer bacak için de uygulayın.</p>
<p style="box-sizing: border-box; font-family: Arial; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; overflow-wrap: break-word; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.32px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    &nbsp;</p>
&nbsp;
</asp:Content>
