<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="asd.aspx.cs" Inherits="WebApplication40.asd" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="article-header" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; color: rgb(35, 31, 32); font-size: 18px; line-height: 22px; position: relative; font-weight: 400; font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;"><span>&nbsp;</span>Faydasından Çok Zararı Dokunan 15 Yanlış Öneri<br />
    </h1>
    <h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">1. Ağırlık çalışmak yağı kasa çevirir.</h2>
    <p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image1" runat="server" Height="222px" ImageUrl="~/im/1res.jpg" Width="394px" />
    </p>
    <p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Yağın kasa dönüşmesi mümkün değildir. Yağ dokusu derinin altında, kasların arasında ya da iç organların etrafında bulunur. Ağırlık çalışmak sizin kas dokunuzu geliştirir. Yağ yakan şey ise diyet yapmak ve sağlıklı beslenmek olacaktır.</span></p>
    <h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">2. Bulmaca ya da sudoku gibi oyunlar beyninize egzersiz yaptırır.</h2>
    <p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image2" runat="server" Height="190px" ImageUrl="~/im/2res.jpg" Width="402px" />
    </p>
    <p style="box-sizing: border-box; margin: 7px 0px 15px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        Aslında birçok araştırmaya göre, bildiğimiz fiziksel egzersiz beyin için bulmaca çözmekten çok daha sağlıklıdır. Kalp atışınızı arttıran, sizi terleten ve hareket ettiren tüm egzersizlerin beyin üzerindeki faydaları araştırmalar tarafından kanıtlandı.</p>
    <p style="box-sizing: border-box; margin: 7px 0px 15px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        Ayrıca hafıza geliştirmek, beyninizi yaşlanmanın etkilerinden korumak için de fiziksel egzersiz yapmanız öneriliyor.</p>
    <h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;"><span>&nbsp;</span>3. Egzersiz yapmak kilo vermenin en hızlı yöntemidir.</h2>
    <p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image3" runat="server" Height="204px" ImageUrl="~/im/3res.jpg" Width="408px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Eğer amacınız kilo vermek ise, bunu sadece spor yaparak ve yediğiniz her şeyi yakacağınızı düşünerek yapamazsınız. Yemek yeme alışkanlıklarınızı kökünden değiştirmeniz gerekiyor.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 4. Egzersiz yaşlanmanın vücuda olan etkilerine karşı etkili bir silah olamaz.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image4" runat="server" Height="201px" ImageUrl="~/im/4res.jpg" Width="403px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Aslında düzenli spor yapmak, hem vücudunuzu hem de beyninizi yaşlanmanın negatif etkilerinden koruyan bir alışkanlıktır. Kalp hastalıkları, tansiyon, kolesterol gibi rahatsızlık risklerinin spor yaparak azaldığı birçok araştırmada ortaya çıkmıştır.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">5. Yaşımız ilerledikçe daha çok kilo almamızın sebebi yavaş bir metabolizmaya sahip olmamızdır.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image5" runat="server" Height="205px" ImageUrl="~/im/5res.jpg" Width="395px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Yapılan araştırmalara göre, 30 yaşından sonra vücudun kalori yakma özelliklerinde pek bir değişiklik görülmemektedir. Yaşa bağlı kilo alımlarında asıl sorumlu hareket seviyesinin düşmesi, insanın daha az aktif olmasıdır.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 6. Formunuzu korumak için haftada bir ya da iki kez spor yapmak yeter.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image6" runat="server" Height="202px" ImageUrl="~/im/6res.jpg" Width="393px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Egzersizlerinizden sonuç almak istiyorsanız, haftada 3 ila 5 kez spor yapmalısınız</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 7. En faydalısı sabah yapılan spordur.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image7" runat="server" Height="184px" ImageUrl="~/im/7res.jpg" Width="388px" />
</p>
<p style="box-sizing: border-box; margin: 7px 0px 15px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
    Aslında sporu yaptığınız saati siz kendinize göre ayarlayıp, bir düzene oturtursanız en çok verimi alırsınız. Yani her gün spor yapabilmek için saat kaç size en uygunsa, o saatte spor yapın!</p>
<p style="box-sizing: border-box; margin: 7px 0px 15px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
    Öte yandan sabah spor yapmanın, gün içinde yağ yakımını hızlandırdığına dair çalışmalar var.</p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 8. Karın kaslarınızı ortaya çıkarmak istiyorsanız, bol bol mekik çekmelisiniz.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image8" runat="server" Height="177px" ImageUrl="~/im/8res.jpg" Width="371px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Egzersiz türü itibariyle mekik ya da yarım mekik, sadece belli bir kas grubunu çalıştırır. Fakat plank yaparsanız, önde, arkada ve yanlarda olmak üzere birçok kas grubu çalış</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 9. Ağırlık çalışmak erkeklere göredir.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <asp:Image ID="Image9" runat="server" Height="192px" ImageUrl="~/im/9res.jpg" Width="381px" />
</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Ağırlık çalışmak, kasları güçlendirmenin en iyi yoludur ve cinsiyet ile hiçbir ilgisi yoktur. Aradaki tek fark, kadınların erkeklere göre daha az testosteron salgılaması ve bazı araştırmaların bu hormonun kasları geliştirmede rol oynadığını göstermesidir.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 10. İki hafta sporu bırakırsanız formunuzu yitirirsiniz.</h2>
    <p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
        <asp:Image ID="Image10" runat="server" Height="184px" ImageUrl="~/im/10res.jpg" Width="376px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Aslında düzenli spor yapan birinin kasları düzenli egzersiz yapmadan geçirdiği bir haftanın sonunda azalmaya başlar. 7 gün hiç spor yapmadan dinlenmek bile, kondisyonun tamamen zayıflamasına yol açar.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 11. Uzun koşular yapmak fit kalmanın sırrıdır</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <asp:Image ID="Image11" runat="server" Height="185px" ImageUrl="~/im/11res.jpg" Width="378px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Aslında kısa fakat hızlı koşular size bir maraton boyunca koşmanın yaptığı etkiyi sunacaktır. Uzun ve dayanıklılık gerektiren egzersizler vücudumuz için faydalı olsa da, birçok araştırma kısa, tempolu ve yoğun spor yapmanın da benzer etkileri olduğunu kanıtlamıştır</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">12. Bir yemek ve spor günlüğü tutmak, nasıl beslendiğinizi kayıt altına almak için güvenilir bir metottur.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <asp:Image ID="Image12" runat="server" Height="198px" ImageUrl="~/im/12res.jpg" Width="381px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Aslında bunu yaparken bile insan, gerçekleri olduğundan daha iyi göstererek kendini kandırmayı seçer.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">13. Spor yaptıktan sonra kaybedilen sıvıyı geri kazanmanın en iyi yolu sporcu içecekleridir.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <asp:Image ID="Image13" runat="server" Height="189px" ImageUrl="~/im/13res.jpg" Width="382px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Çoğu sporcu içeceği sadece su ve şekerden oluşur. Spordan sonra bol su içmek, ve yüksek protein değerli bir atıştırmalık yemek vücudunuzun ihtiyacı olan yakıtı fazlasıyla sağlar. Aman şeker içeriklerine dikkat!</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">14. Vücut kitle endeksi çok önemli bir rakamdır, sağlığımız ile ilgili pek çok bilgi verir.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <asp:Image ID="Image14" runat="server" Height="195px" ImageUrl="~/im/14res.jpg" Width="382px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Hayır aslında bu rakam sadece vücudumuzun boy ve kilo oranının ne kadar sağlıklı olup olmağını gösterir. Vücudumuzdaki yağ ne kadar fazla ise, kalp sağlığımız, diyabet riskimiz ve yaşa bağlı zihinsel sağlığımız tehlikeye girer.</span></p>
<h2 class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">&nbsp; 15. Terlemezseniz yaptığınız spor işe yaramamış demektir.</h2>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <asp:Image ID="Image15" runat="server" Height="187px" ImageUrl="~/im/15res.jpg" Width="380px" />
        
    </p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    <span style="color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Sizi hareketlendirip, nefes almanızı ve kalp atışınızı hızlandırmanızı sağlayan her egzersiz, düzenli yapıldığı taktirde sağlıklıdır.</span></p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        
    &nbsp;</p>
<p class="content-counter content-title" data-v-74ba1eb3="" style="box-sizing: border-box; margin: 15px; font-weight: 700; font-size: 17px; padding-top: 5px; color: rgb(74, 74, 74); font-family: &quot;PT Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 253); text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
</asp:Content>
